### ISSUE TITLE
Default Cortana Music Player

### ISSUE THREAD

**Issue by anggiedwarsa** [UrbanCMC/foo_wpl#1]
Hello. Please fix this. After I instal this component, now I set .wpl file use foobar as default program, because I want Cortana play music with foobar. But If Cortana want to play music, it always ask for default program, I have checked "always use this app to open .wpl file", but still asking if open the .wpl file. :( I don't know if the problem from this component or my computer. I'm sure I have associate .wpl file with foobar in control panel.
![screenshot 8](https://cloud.githubusercontent.com/assets/15307788/10714726/3d446f24-7b2e-11e5-8f5c-f6c79819c05d.png)

**Comment by UrbanCMC** [comment]
Hello and thank you for reporting this problem.
I took some time and had a closer look at this issue. It seems to be a general problem between foobar2000 and windows search, because you get the exact same problem if you try to open any file associated to foobar2000 from the search results window. If, however, you were to open the file through the windows explorer, foobar2000 would be opened correctly.

I'm not sure that this is something that I can solve from the component's side, but rather a problem the devs of foobar itself need to fix.
That said, I'll still try to find a solution. Just know that it might take some time.

**Comment by anggiedwarsa** [comment]
Okay. Please notify if you can solve the problem via component, But I think the problem is via component, because I also try set foobar to run as administrator, and the .wpl file icon is also not .wpl, but foobar component. Please notify if you can solve the problem. And big thanks for respond. :)

**Comment by UrbanCMC** [comment]
The problem has been resolved in the latest beta version of [foobar2000](https://www.foobar2000.org/download) (1.3.9 Beta 5). After installing that version, everything should work just as expected.

**Comment by anggiedwarsa** [comment]
Oh yea? Thank you so much, I'll try to instal in. Thank you.
