### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by vmaudio** [UrbanCMC/foo_wpl#3]
Hello,
I'm using Win10 Version 10586 with Cortana, foobar2000 v1.3.10 and your plugin. The WPL file type assotiation is set to foobat as a default. Foobar is set to be as a default audio player in Win.
All things considered Cortana still opens Groove, when I ask to open music. When I ask to play or pause music, nothing happens, not even Groove opens. Cortana understands me correctly. I have been trying for two hours. Please help

**Comment by UrbanCMC** [comment]
I'm sorry to say that there isn't really much I can do about this.
There was an update to Cortana sometime around November last year, which changed Cortana's music functionality to use the MSWINDOWSMUSIC protocol instead of .wpl playlists.

As far as I'm aware there isn't any way to reassign that protocol to another application, but even if it was possible, foobar2k wouldn't know how to handle it at the moment anyway.

If there was any way to change that I might be able to try and create a plugin for it, but it doesn't look like that would happen any time soon.

**Comment by vmaudio** [comment]
Well you probably should inform potential users it no longer works. It had cost me a few hours of my life to find out.

**Comment by UrbanCMC** [comment]
Well, to be fair the plugin works absolutely fine. It still allows foobar2k to read/write .wpl playlists, which is the only thing it ever did.
But I get your point and will put a notice up.
